ryoppippi/unplugin-typia

examples/sveltekit/vite.config.ts, packages/unplugin-typia/src/core/index.ts, packages/unplugin-typia/src/core/options.ts
The verbose option in unplugin-typia has been replaced with a log option. This new option can be set to either a boolean value or 'verbose'. This change provides more control over the logging behavior of the plugin and aligns with common logging practices.
=> feat(unplugin-typia): Replace `verbose` with `log`

packages/unplugin-typia/src/core/typia.ts
This commit modifies the `transformTypia` function to cache the TSConfig after the first read. This prevents multiple reads of the same file, improving performance. The TSConfig is now stored in a variable and only read if it hasn't been defined yet.
=> feat(unplugin-typia): cache TSConfig to avoid multiple reads

packages/unplugin-typia/src/core/options.ts
This commit allows the cache option to accept a boolean value. If `true`, it enables cache with a default path. If `false`, it disables cache. If an object is provided, it enables cache with a custom path. The default value is `{ enable: true, base: '/tmp'}`.
=> feat(options): allow boolean for cache option

packages/unplugin-typia/src/core/options.ts
This commit introduces a new type, ResolvedOptions, which is used to represent the resolved options. This change simplifies the type annotation for the defaultOptions constant and the return type of the resolveOptions function.
=> feat(options): introduce ResolvedOptions type

.github/workflows/ci.yaml
This commit introduces a new step in the CI workflow that performs a dry-run of the package publishing process. This step is crucial for ensuring that the package is ready for publishing and will not encounter any issues during the actual publish process.
=> feat(ci): Add publish dry-run step to CI workflow

packages/unplugin-typia/README.md
The examples list in the README has been expanded to include more
specific use cases. This includes examples for vite-vanilla, vite-react,
vite-hono, sveltekit, esbuild, and nextjs.
=> feat(README): update examples list

packages/unplugin-typia/README.md
The installation instruction for `unplugin-typia` was duplicated in the README.md file. This commit removes the duplicate instruction to avoid confusion for users.
=> fix(readme): remove duplicate installation instruction

packages/unplugin-typia/src/core/cache.ts, packages/unplugin-typia/src/core/options.ts
This pull request introduces several enhancements to the cache handling and validation in the `unplugin-typia` package:
1. Added a new `StoreData` interface to store additional metadata alongside the cached data, including the `id` and `source` properties. This allows for more robust cache validation.
2. Updated the `getCache` function to perform cache validation by comparing the stored `id` and `source` with the provided values. If there is a mismatch or the data is not found, `null` is returned.
3. Modified the `setCache` function to store the `StoreData` object, including the `data`, `id`, and `source` properties. If the provided `data` is `null`, the cache entry is removed using `removeItem`.
4. Refined error handling in the `getStorage` function by throwing a more descriptive error …
=> Improve cache handling and validation in unplugin-typia

.github/workflows/deploy.yaml, package.json, turbo.json
This commit introduces a new GitHub Actions workflow for deployment. It triggers on push to the main branch and on workflow dispatch. The workflow uses the setup-bun action with the latest bun version, installs dependencies with bun i --frozen-lockfile, and runs the newly added "deploy" script from package.json.
The "deploy" script has also been added as a dependency in turbo.json. A CLOUDFLARE_API_TOKEN environment variable is used during deployment, which is fetched from GitHub secrets.
=> feat: Add deployment workflow and script

.github/workflows/deploy.yaml
An environment named 'main-example-deploy' has been added to the deploy job in the GitHub Actions workflow. This environment will be used for deploying the main example.
=> feat(deploy.yaml): add environment to deploy job

packages/unplugin-typia/src/core/index.ts
The Options type has been exported from the core module. This change
provides better type support for external usage.
=> feat(core): export Options type from core

packages/unplugin-typia/src/core/options.ts, packages/unplugin-typia/src/core/typia.ts
This commit introduces a new option 'tsconfig' in the plugin options.
This option allows users to specify the path to the tsconfig file.
If not specified, the plugin will try to find it automatically.
The 'tsconfig' option is also added to the 'ResolvedOptions' type.
The 'getTsCompilerOption' function now accepts an optional 'tsconfigId'
parameter, which is used when reading the tsconfig file.
=> feat: add tsconfig path option to plugin options

examples/bun-build/build.ts, examples/bun-build/package.json, packages/unplugin-typia/README.md, packages/unplugin-typia/src/bun.ts
This commit adds two examples of how to use the unplugin-typia with
Bun.build in the README.md and bun.ts files. The first example shows
how to use it for running scripts, and the second one for building
scripts. It also updates the documentation in bun.ts to include these
examples and a link to the Bun.build documentation.
=> feat(unplugin-typia): add Bun.build examples to README and bun.ts/ enable cache for bun.ts

package.json, packages/unplugin-typia/package.json, turbo.json
A new script 'format' has been added to the scripts section of
package.json in both the root directory and the unplugin-typia
package. This script will run the 'eslint --fix .' command to
automatically format the code according to the project's ESLint
rules. The turbo.json file has also been updated to include a
dependency for the 'format' script.
=> feat: add format script to package.json

packages/unplugin-typia/README.md, packages/unplugin-typia/src/bun.ts, packages/unplugin-typia/src/esbuild.ts, packages/unplugin-typia/src/farm.ts, packages/unplugin-typia/src/next.ts, packages/unplugin-typia/src/rolldown.ts, packages/unplugin-typia/src/rollup.ts, packages/unplugin-typia/src/rspack.ts, packages/unplugin-typia/src/vite.ts, packages/unplugin-typia/src/webpack.ts
The import paths for the 'unplugin-typia' package have been updated
to use the scoped package name '@ryoppippi/unplugin-typia'. This
change has been applied across all files where the package is
imported.
=> feat: change import paths to scoped package

packages/unplugin-typia/README.md, packages/unplugin-typia/src/webpack.ts
This commit modifies the webpack plugin to support 'cjs' target by using 'jiti'. The previous version only supported 'esm' target. The usage example in the comments has been updated to reflect this change.
Refer to the issue https://github.com/samchon/typia/issues/1094 for more details.
=> feat(webpack): support 'cjs' target with 'jiti'

.github/workflows/jsr.yaml, packages/unplugin-typia/jsr.json, packages/unplugin-typia/package.json
This commit introduces a new GitHub workflow named 'jsr'. This workflow is triggered on push events for tags and on workflow dispatch. It sets up the environment with the latest version of 'bun', installs dependencies, fetches the version from the tag, updates the version in package.json and jsr.json, and finally publishes the package if the ref is a version tag.
=> feat: Add GitHub workflow for publishing package

.github/workflows/jsr.yaml
This commit introduces a new GitHub workflow named 'jsr'. It triggers
on push events for tags starting with "v". The workflow has read
permissions for contents and write permissions for id-token. It
runs on ubuntu-latest and includes steps for checkout, install
dependencies with frozen lockfile, and publish from the
'packages/unplugin-typia' directory.
=> feat: Add GitHub workflow for jsr

packages/unplugin-typia/src/core/cache.ts
The id field in StoreData is removed as it's no longer needed. The changes are reflected in getCache and setCache functions. The condition in getCache and the JSON stringify in setCache are updated accordingly.
=> feat(cache): remove id from StoreData

packages/unplugin-typia/README.md, packages/unplugin-typia/src/bun.ts
This commit adds a note about a limitation when using the script. Users need to import the `typia` module as a default import in their script. Type named import is fine. This is due to a bug in `Bun`. A link to the related issue is also provided for more context.
=> feat(README): add limitation note for Bun.runtime usage

packages/unplugin-typia/README.md
This PR removes the section in the README that describes a limitation related to the import of the `typia` module. The limitation was that `typia` had to be imported as a default import in scripts, and named imports were not allowed. This was due to a bug in `Bun`. 
The removal of this section suggests that the bug has been fixed and the limitation no longer applies. Users can now import `typia` in any way they prefer in their scripts.
fixes: #99
=> fix(readme): remove limitation section

packages/unplugin-typia/src/bun.ts, packages/unplugin-typia/src/core/utils.ts
This commit introduces a new utility function `isBun` which checks if
`globalThis.Bun` is not nullish. This function is now used in `bun.ts` to
throw an error if the plugin is not used with bun.
=> feat: add isBun utility function

packages/unplugin-typia/src/bun.ts
The condition for checking if the environment is 'bun' was incorrect.
It was throwing an error when it was 'bun', but it should throw an
error when it is not 'bun'. This commit corrects this condition.
=> fix(bun.ts): correct condition for bun check

examples/bun-build/preload.ts
This commit enables caching and sets the logging level to verbose
for the UnpluginTypia plugin in the bun-build example. This change
should improve performance and provide more detailed logs for
debugging.
=> feat(examples/bun-build): Enable cache and verbose logging in UnpluginTypia

packages/unplugin-typia/src/core/cache.ts
This PR refactors the synchronous file operations in `cache.ts` to use asynchronous versions. The changes include:
- Replaced synchronous file operations from `node:fs` with their asynchronous counterparts from `node:fs/promises`.
- Updated the `getCache` function to use asynchronous file operations. Added conditionals to handle different environments (Bun and non-Bun).
- Updated the `setCache` function to use asynchronous file operations. Added conditionals to handle different environments (Bun and non-Bun).
- Updated the `prepareCacheDir` function to use asynchronous file operations and made it an async function.
- Updated the `isWritable` function to use asynchronous file operations and made it an async function.
These changes improve the performance of the application by not blocking …
=>  Refactor Synchronous File Operations to Asynchronous & use Bun

packages/unplugin-typia/src/core/cache.ts, packages/unplugin-typia/src/core/options.ts
This commit updates the cache directory handling in the unplugin-typia package. It introduces a new function `getCacheDir` that determines the cache directory based on the system's temporary directory. This function also includes a workaround for an issue with pnpm setting an incorrect `TMPDIR`. The default cache base path has been updated to use this new function. The changes are reflected in the `Options` interface and the default options.
=> feat(cache): update cache directory handling

packages/unplugin-typia/src/bun.ts, packages/unplugin-typia/src/core/cache.ts, packages/unplugin-typia/src/core/index.ts, packages/unplugin-typia/src/core/options.ts, packages/unplugin-typia/src/core/types.ts, packages/unplugin-typia/src/core/typia.ts, packages/unplugin-typia/test/cache.ts, packages/unplugin-typia/test/options.ts, packages/unplugin-typia/test/typia.ts
This PR introduces several changes to the `unplugin-typia` package, primarily focusing on type safety and code refactoring. Here are the key changes:
1. **Introduction of Tagged Types**: The PR introduces several new tagged types (`ID`, `Source`, `CacheKey`, `CachePath`, `FilePath`) to improve type safety across the codebase. These types are used to wrap and unwrap values, ensuring that they are used correctly in their respective contexts.
2. **Refactoring of Transform Functions**: The transform functions in `bun.ts` and `typia.ts` have been refactored to use the new tagged types. This includes the introduction of a new `taggedTransform` function in `bun.ts`.
3. **Changes to Cache Handling**: The cache handling functions in `cache.ts` have been updated to use the new tagged types. This …
=> Refactor code to use tagged types for better type safety

packages/unplugin-typia/src/core/cache.ts, packages/unplugin-typia/src/core/index.ts, packages/unplugin-typia/src/core/types.ts, packages/unplugin-typia/src/core/typia.ts, packages/unplugin-typia/test/cache.ts
This PR includes several changes to the `unplugin-typia` package, primarily focused on refactoring the handling of the `Data` type and adjusting import statements for better clarity and organization.
1. In `core/cache.ts`, the `Data` type has been imported from `types.js` instead of being defined within the file. The `transformTypia` import has been removed. The `data` variable's type has been changed from `Data` to `string`.
2. In `core/index.ts`, the import statement has been adjusted to separate type imports from regular imports for better clarity.
3. In `core/types.ts`, a new `Data` type has been added.
4. In `core/typia.ts`, the `Data` type has been imported from `types.js`. The `transformTypia` function now returns a `Promise<Data>` instead of `Promise<string>`, and the returned …
=>  Refactor Data Type and Import Statements in unplugin-typia

packages/unplugin-typia/src/core/cache.ts
The cache validation logic in `getCache` function has been updated. Previously, it returned the cache data if it ended with `hashComment`. Now, it returns null if the data does not end with `hashComment`, indicating that it's not a valid cache. This change improves the accuracy of cache validation.
=> feat(cache): cosmetic cache validation logic

packages/unplugin-typia/src/core/typia.ts
This PR introduces a using result statement for handling transformation results in the transformTypia function, and enhances the resource disposal mechanism within the transform function. These changes aim to simplify the transformation process and ensure proper cleanup of resources.
1. Introduction of using result:
Replaced the separate declaration and extraction of diagnostics, transformed, and file with a using result statement.
This change provides a more concise and readable approach to handling the transformation results.
2.Enhanced Resource Disposal:
Introduced a [Symbol.dispose] method within the returned object of the transform function.
This ensures that the transformationResult.dispose() is called properly, facilitating better resource management and preventing potential memory …
=> Refactor Typia Transformation: Introduce using result and Improve Resource Disposal

examples/bun-build/package.json
The build script in the bun-build package.json file has been updated.
Previously, it was directly building the index.ts file. Now, it runs
the build.ts file instead. This change provides more flexibility for
the build process.
=> feat: change build script in bun-build package.json

packages/unplugin-typia/src/core/cache.ts, packages/unplugin-typia/src/core/index.ts, packages/unplugin-typia/test/cache.ts
The cache operations were previously handled by separate functions. This commit refactors the cache operations into a class, providing a more structured and object-oriented approach. The Cache class provides methods for getting and setting cache data, and handles hash key generation and cache directory management internally. This change simplifies the cache usage in the main codebase.
=> refactor(cache): convert cache operations to a class

.github/FUNDING.yaml
This commit introduces a new FUNDING.yaml file under the .github
directory. The file contains a link to the GitHub sponsorship page for
the user 'ryoppippi'.
=> feat(FUNDING): add GitHub sponsorship link

packages/unplugin-typia/package.json
This commit changes the typescript dependency version from caret (^)
version to tilde (~) version. This ensures that only patch updates are
allowed, providing more stability to the project.
=> fix(package.json): pin typescript version to ~5.4.5

.github/workflows/release.yaml
This commit moves the permissions block for contents read and id-token write
from the second job to the first job in the GitHub Actions workflow. This
change ensures that the permissions are set correctly for the workflow.
=> feat: update permissions in release.yaml

packages/unplugin-typia/src/core/cache.ts
The `readPackageJSON` function was used to get the version of 'typia'.
This has been replaced with a direct import from 'typia/package.json'.
This change simplifies the code and reduces the number of dependencies.
=> feat(cache): replace readPackageJSON with direct import

.gitignore, packages/unplugin-typia/package.json
This commit modifies the lint and format scripts in the package.json
file of the unplugin-typia package to use eslint's cache feature. This
improves performance by only linting files that have changed since the
last linting run.
=> feat(eslint): use cache for linting and formatting

packages/unplugin-typia/jsr.json
The version of the package "@ryoppippi/unplugin-typia" has been updated
from 0.4.16 to 0.5.0. This is a minor version update indicating new
features or significant changes.
=> feat: bump version to 0.5.0

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, .github/workflows/release.yaml
This commit adds a 10-minute timeout to each job in the GitHub Actions workflows. This is to prevent jobs from running indefinitely and consuming unnecessary resources. The change affects the following workflows: ci.yaml, deploy.yaml, and release.yaml.
=> feat(ci): add timeout to GitHub Actions workflows

examples/esbuild/build.ts, examples/sveltekit/vite.config.ts
This commit simplifies the cache configuration in UnpluginTypia by
changing the `cache` option from an object to a boolean. This change
affects both the esbuild and sveltekit examples. The `cache` option
now directly takes a boolean value to enable or disable caching.
=> feat: Simplify cache configuration in UnpluginTypia

packages/unplugin-typia/package.json, packages/unplugin-typia/src/core/languages/svelte.ts
The Svelte dependency version has been updated from 'next' to '^5.0.0-next.183'. This change has been reflected in both the bun.lockb and package.json files. The Svelte dependency has also been moved from 'peerDependencies' to 'devDependencies' in the package.json file.
=> refactor(core/svelte): dependency resolution

packages/unplugin-typia/README.md
This commit adds a new section to the README that lists the file
extensions supported by the plugin. This includes `.ts`, `.tsx`, `mts`,
`mtsx`, and `.svelte` (only script tag with `lang="ts"`). This change
provides clarity to users about which file types they can use with the
plugin.
=> docs(README): Add supported file extensions section to README

packages/unplugin-typia/src/core/index.ts
The comparison between the source and the code was removed from the
unpluginFactory function. This comparison was deemed unnecessary as it
was causing the function to exit prematurely in cases where the source
and code were identical, which is not always an undesired scenario.
=> refactor: remove redundant code comparison

packages/unplugin-typia/src/core/index.ts
The `unwrap` function was imported from `types.js` in `core/index.ts`, but it was not being used in the file. This commit removes the unused import to clean up the code and reduce potential confusion.
=> refactor(core/index.ts): remove unused import

packages/unplugin-typia/src/core/languages/svelte.ts, packages/unplugin-typia/src/core/utils.ts
This commit introduces a new utility function, dynamicImport, which is used to dynamically import modules. This function is now used in the Svelte language file to import the Svelte compiler. This change improves the code readability and maintainability.
=> feat(utils.ts): add dynamicImport utility function (fixes: fixes: #198)

packages/unplugin-typia/src/core/cache.ts
fixes: #212 #194
The previous static import of typia's package.json was replaced with a dynamic import using createRequire. This change allows for more flexibility and compatibility with different module systems.
=> fix(cache): use `createRequire` to dynamically import `package.json`

packages/unplugin-typia/src/core/index.ts
The MagicString overwrite method was previously using the source length as the end parameter. This has been adjusted to use -1, which represents the end of the string. This ensures that the overwrite operation correctly replaces the entire source string.
=> refactor(core): use -1 as end parameter for MagicString

packages/unplugin-typia/src/core/options.ts, packages/unplugin-typia/test/options.ts
=> feat(core/options): BREAKING CHANGE cache is disabled by default

packages/unplugin-typia/src/core/typia.ts
The parameters of the transformTypia function have been simplified. The 'id' and 'source' parameters are now wrapped inside the function, which simplifies the function call. The 'id' is also directly used in the 'transformed.find' function, removing the need for 'resolvedId'.
=> refactor(core): move resolve function

packages/unplugin-typia/src/core/typia.ts
This commit refactors the warning message handling in the typia.ts file.
related: #269
=> fix: the way to detect warn function is available

packages/unplugin-typia/src/core/typia.ts
This change modifies the `getTsCompilerOption` function to directly resolve
the path of a provided `tsconfigId`. If no `tsconfigId` is provided, it
falls back to the `resolveTSConfig` function. This provides more flexibility
in tsconfig resolution.
Related : #269
=> fix: tsconfig path resolution

packages/unplugin-typia/src/core/typia.ts
Refactored the module resolution logic to properly handle cases where
aliases are used. This change ensures that if a module is not resolved,
the alias is checked and used for resolution if available. This improves
the robustness of the module resolution process.
=> fix(core): handle module resolution with aliases

packages/unplugin-typia/src/core/cache.ts
Refactored the code to handle dynamic import for fetching the typia
version. Added a fallback mechanism to use createRequire if the
dynamic import fails. This ensures compatibility with different
environments and improves robustness.
=> fix(cache): handle dynamic import for typia version

packages/unplugin-typia/README.md, packages/unplugin-typia/src/webpack.ts
Updated the README and webpack plugin usage notes to provide clearer instructions for using the plugin with different Node.js versions. Added specific instructions for Node < 20.17.0 and Node >= 20.17.0, including the use of `jiti` and the `--experimental-require-modules` flag.
=> feat: update README and webpack plugin usage notes

examples/webpack-minimal/webpack.config.ts, packages/unplugin-typia/README.md, packages/unplugin-typia/src/webpack.ts
Reverts ryoppippi/unplugin-typia#330
=> Revert "simplify webpack config"

packages/unplugin-typia/src/core/typia.ts
Typescript compiler was unable to resolve module alias path because the pathBaseAlias contains `tsconfig.ts` where it should only be its `dirname`
This PR fixes #338
=> fix(#338): basePath contains tsconfig.json

packages/unplugin-typia/package.json
This pull request includes an update to the `packages/unplugin-typia/package.json` file to enhance the package's compatibility and flexibility with additional peer dependencies and metadata.
* Added `svelte` and `vite` as optional peer dependencies to support broader usage with these frameworks.
* Included `typescript` as a peer dependency to specify the compatible version range, ensuring proper TypeScript integration.
* Introduced `peerDependenciesMeta` to mark `svelte` and `vite` as optional, allowing users to choose whether to include these dependencies.
=> fix(package.json): peer deps

bun.lock, examples/bun-build/index.ts, examples/bun-build/package.json, examples/nextjs/package.json, examples/sveltekit/package.json, examples/vite-hono/package.json, examples/vite-react/package.json, examples/webpack-minimal/package.json, packages/unplugin-typia/package.json, packages/unplugin-typia/tests/fixtures/__snapshots__/alias.ts, packages/unplugin-typia/tests/fixtures/__snapshots__/esbuild/random.js, packages/unplugin-typia/tests/fixtures/__snapshots__/random.ts, packages/unplugin-typia/tests/fixtures/__snapshots__/rollup/random.js, packages/unplugin-typia/tests/fixtures/__snapshots__/vite/alias.js, packages/unplugin-typia/tests/fixtures/__snapshots__/vite/random.js
This pull request includes several updates across multiple files, primarily focusing on upgrading the `typia` dependency to version `9.0.1` and making adjustments to the random integer generation logic in various snapshot test files.
* Updated `typia` dependency from `^8.0.3` to `^9.0.1` in multiple `package.json` files across different example projects. [[1]](diffhunk://#diff-7901be6bfcc73b2dd78e4517b78e223cc80273c2c9590d659ef928a692a86fc3L16-R16) [[2]](diffhunk://#diff-23044c563f1173db6464d127497c342c8f7f90722764a37749681bf455a515e0L25-R25) [[3]](diffhunk://#diff-1daf89086eff276473621b72647a0c0097e3b3e70d21fadf9ba044621ebf1b74L25-R25) [[4]](diffhunk://#diff-4750f20ee6e8f169374673f9274cacf5e93bdae025bd6910b35abe0361d6b26dL23-R23) …
=> chore: update typia peerDependency

bun.lock, packages/unplugin-typia/package.json, packages/unplugin-typia/src/core/cache.ts
This pull request introduces a new dependency, `fs-fixture`, and integrates it into the `cache.ts` file to enhance testability by replacing the use of `tmpdir()` with dynamically created fixtures. Below are the most important changes grouped by theme.
* [`packages/unplugin-typia/package.json`](diffhunk://#diff-cddf85f2cd0f1df90dea84161c47eb60b072d7c7b688b6d680615b3a0c65a4eeR123): Added `fs-fixture` as a new dependency to support the creation of temporary file fixtures for testing.
* [`packages/unplugin-typia/src/core/cache.ts`](diffhunk://#diff-2498f43e710738e5e015c1027a02b6b49fcc83f0f3f3bb935dba3c92ccbd77c2L2-R5): Imported `createFixture` from `fs-fixture` and removed the import of `tmpdir` from `node:os`.
* [`packages/unplugin-typia/src/core/cache.ts`](diffhunk://#diff-2498f43e710738e5e0 …
=> test: use fs-fixture for creating tmp dir
